title: Mindulle's bookshelf📚

baseurl: /bookshelf/
url: https://mindulle.github.io/bookshelf

collections_dir: docs
collections:
  Books:
    output: true
  Items:
    output: true
  Missions:
    output: true
  Monsters:
    output: true
  Production:
    output: true
  Quests:
    output: true
  Talent:
    output: true
  Skills:
    output: true
  Weapons:
    output: true

defaults:
  - scope:
      path: "docs/_books/:name"
      type: "books"
    values:
      layout: "foam"
  - scope:
      path: "docs/_items/:name"
      type: "items"
    values:
      layout: "foam"
  - scope:
      path: "docs/_missions/:name"
      type: "missions"
    values:
      layout: "foam"
  - scope:
      path: "docs/_monsters/:name"
      type: "monsters"
    values:
      layout: "foam"
  - scope:
      path: "docs/_production/:name"
      type: "production"
    values:
      layout: "foam"
  - scope:
      path: "docs/_quests/:name"
      type: "quests"
    values:
      layout: "foam"
  - scope:
      path: "docs/_talent/:name"
      type: "talent"
    values:
      layout: "foam"
  - scope:
      path: "docs/_skills/:name"
      type: "skills"
    values:
      layout: "foam"
  - scope:
      path: "docs/_weapons/:name"
      type: "weapons"
    values:
      layout: "foam"

highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

repository: mindulle/bookshelf

# Generate permalinks in format specified in: https://jekyllrb.com/docs/permalinks/#built-in-formats
permalink: pretty

plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-relative-links

sass:
  sass_dir: _sass
  style: compressed
