title: Mindulle's bookshelf📚

baseurl: /bookshelf/
url: https://mindulle.github.io/bookshelf

collections_dir: docs/
collections:
  Books:
    output: true
    permalink: /:collection/:name
  Items:
    output: true
    permalink: /:collection/:name
  Missions:
    output: true
    permalink: /:collection/:name
  Monsters:
    output: true
    permalink: /:collection/:name
  Production:
    output: true
    permalink: /:collection/:name
  Quests:
    output: true
    permalink: /:collection/:name
  Talent:
    output: true
    permalink: /:collection/:name
  Skills:
    output: true
    permalink: /:collection/:name
  Weapons:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: "books"
      type: "books"
    values:
      layout: "foam"
  - scope:
      path: "items"
      type: "items"
    values:
      layout: "foam"
  - scope:
      path: "missions"
      type: "missions"
    values:
      layout: "foam"
  - scope:
      path: "monsters"
      type: "monsters"
    values:
      layout: "foam"
  - scope:
      path: "production"
      type: "production"
    values:
      layout: "foam"
  - scope:
      path: "_quests"
      type: "quests"
    values:
      layout: "foam"
  - scope:
      path: "_talent"
      type: "talent"
    values:
      layout: "foam"
  - scope:
      path: "_skills"
      type: "skills"
    values:
      layout: "foam"
  - scope:
      path: "_weapons"
      type: "weapons"
    values:
      layout: "foam"

highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

repository: mindulle/bookshelf

# Generate permalinks in format specified in: https://jekyllrb.com/docs/permalinks/#built-in-formats
permalink: pretty

plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-relative-links

sass:
  sass_dir: _sass
  style: compressed
