title: Mindulle's bookshelf📚

baseurl: /bookshelf
url: https://mindulle.github.io

collections_dir: collection
collections:
  anti-pattern:
    output: true
  design-pattern:
    output: true
  laws:
    output: true
  uml:
    output: true
    

highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

repository: mindulle/bookshelf

# Generate permalinks in format specified in: https://jekyllrb.com/docs/permalinks/#built-in-formats
permalink: pretty

plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-relative-links

sass:
  sass_dir: _sass
  style: compressed
